[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
raydium_cpi = "7vQYvV51BsKTZErQuX22K2nF2F9YsY1baQSBR956UpU5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
